// <auto-generated />
using HouseHoldItems.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HouseHoldItems.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221022085845_SeedProductsTable")]
    partial class SeedProductsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HouseHoldItems.Models.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Cost = 500.0,
                            Description = "plastic chair",
                            Name = "Plastic chair",
                            ProductCategory = 1
                        },
                        new
                        {
                            ProductId = 2,
                            Cost = 5000.0,
                            Description = "Office chair",
                            Name = "Office chair",
                            ProductCategory = 1
                        },
                        new
                        {
                            ProductId = 3,
                            Cost = 50000.0,
                            Description = "Laptop",
                            Name = "Hp Laptop",
                            ProductCategory = 0
                        },
                        new
                        {
                            ProductId = 4,
                            Cost = 5000.0,
                            Description = "Utensils",
                            Name = "Pressure cooker",
                            ProductCategory = 2
                        },
                        new
                        {
                            ProductId = 5,
                            Cost = 2500.0,
                            Description = "Cooking gas",
                            Name = "Cooking gas",
                            ProductCategory = 2
                        },
                        new
                        {
                            ProductId = 6,
                            Cost = 3000.0,
                            Description = "Carpet",
                            Name = "Carpet",
                            ProductCategory = 3
                        },
                        new
                        {
                            ProductId = 7,
                            Cost = 25000.0,
                            Description = "Mobile phone",
                            Name = "Samsung Galaxy",
                            ProductCategory = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
